---
- name: return next available IP address for network {{ network }}
  ansible.builtin.set_fact:
    ipaddr: "{{ lookup('infoblox.nios_modules.nios_next_ip', network, 
                provider=nios_provider) }}"

- name: print ip
  ansible.builtin.debug:
    var: ipaddr

- name: set the fact for the IP address
  ansible.builtin.set_fact:
    nios_next_ip_address: "{{ ipaddr }}"

- name: Set the stat for the IP Address
  ansible.builtin.set_stats:
    data:
      nios_next_ip_address: "{{ ipaddr }}"

