namespace: rsoliman
name: infoblox_demos
version: 1.0.0
readme: README.md
authors:
- Raed Soliman <raedrizk@gmail.com>

description: A collection of roles used to demo Infoblox automation using Ansible.

license:
- "MIT"

tags: ['infoblox','demo','ansible','raedrizk','rsoliman']

dependencies:
    "infoblox.nios_modules": "*"
    "ansible.builtin": "*"

repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
