---
nios_provider:
  host: "{{ infoblox_host }}"
  username: "{{ infoblox_username }}"
  password: "{{ infoblox_password }}"

new_host_name: "{{ ec2_name_tag_choice if (ec2_name_tag_choice is defined and ec2_name_tag_choice != '') else new_host_name_choice | default('host.ansible.com') }}"
